### ISSUE TITLE
автозагрузка

### ISSUE THREAD

**Issue by maugly402** [curzon01/mqtt2sql#10]
Здравствуйте! 
не получается добавить в автозагрузку скрипт работает 2 секунды и вылетает, с теми же параметрами запускаю из терминала все работает

**Comment by curzon01** [comment]
Sorry, english only.
and without providing files used by yourself I can't help you

**Comment by maugly402** [comment]
Thank you to perform autoloading it turned out it was necessary to issue the necessary access rights and specify the full path to the database in the configuration file
[mqtt2sql_conf.txt](https://github.com/curzon01/mqtt2sql/files/5725973/mqtt2sql_conf.txt)
I Express my gratitude to You now everything works

**Comment by curzon01** [comment]
thx for the hint but valid access rights are basics and prerequisites for every running program that wants to access data. This is nothing specific.
