### ISSUE TITLE
anyone have any consumer of the SQL data?

### ISSUE THREAD

**Issue by hartmark** [curzon01/mqtt2sql#13]
I found this great project and it's perfect for me to get the mqtt data from my home automation system.

The next step for me is to take this historic data and plot it so I can get graphs for my data. And I thought that perhaps someone have already one working solution to share in GitHub 😀

I'm going to try write a graphing solution using react and perhaps .net as backend part.

**Comment by curzon01** [comment]
Pls use the section [Discussions](https://github.com/curzon01/mqtt2sql/discussions) for such a conversation
Issues is used on Github to track bugs, tickets etc.
