### ISSUE TITLE
Change python to python3 in the instructions

### ISSUE THREAD

**Issue by gatorback** [curzon01/mqtt2sql#26]
Change python to python3 in the instructions

**Comment by curzon01** [comment]
python is python3, other python are [EOL](https://www.python.org/doc/sunset-python-2/)  for at least 4 years already.

It has also already been described:

> During the installation we
> create a usable [Python 3.x](https://www.python.org/downloads/) environment

> If not already done, install a working [Python 3.x](https://www.python.org/downloads/) environment described there.
> Note: Due to the https://github.com/python/devguide/pull/344 in Jan 2020 Python 2.x is no longer supported.
