### ISSUE TITLE
mysql.sql line 94: 'IF NOT EXISTS' causes an error

### ISSUE THREAD

**Issue by gatorback** [curzon01/mqtt2sql#29]
CREATE VIEW IF NOT EXISTS `mqtt_history_view` AS
                 XXXXXXXXXXXXXX

VIEW IF NOT EXISTS is unsupported per https://stackoverflow.com/a/78208913/4953146

Deleted  VIEW IF NOT EXISTS => script ran without errors

**Comment by curzon01** [comment]
this comes from Maria DB, which allows this
