### ISSUE TITLE
Errors in readme

### ISSUE THREAD

**Issue by rugalash** [curzon01/mqtt2sql#7]
Hello thanks for this script it seems like the least bloat option to throw my mqtt messages into an sqlite database.

I think there are a few errors on the readme, I could be wrong though (all of these you can ctrl+f to find)

I don't think the second --sqldb mqtt -v is correct, I tested various things with it and just got errors:
--sqldb mqtt.db --sqldb mqtt -v
should be:
--sqldb mqtt.db

Where you say this:
Insert the following lines - note: replace example usernames and passwords with yours

Is this accurate? I don't see where any users or passwords are at all. Normally if you want a user you'd do systemctl enable programname@username.service right? But you do not have that so it just goes as your current users' service?

Thanks

**Comment by curzon01** [comment]
2. parameter meant the table so parameter was wrong (should be `...--sqldb mqtt.db --sqltable mqtt -v`), not the argument.

the note referred to an old version in which the parameters were not yet transferred in a .conf file - has nothing to do with systemctl
