### ISSUE TITLE
mqtt2sql.py: error: argument --sql-type: invalid choice: 'mysql' (choose from 'sqlite')

### ISSUE THREAD

**Issue by zeesser** [curzon01/mqtt2sql#8]
Why I can't choose MySQL?

actually, I use MariaDB, so which type I should choose？

**Comment by gsantner** [comment]
mysql=mariadb

**Comment by zeesser** [comment]
./mqtt2sql.py --mqtt-host localhost --mqtt-topic '#' --sql-host localhost --sql-username root --sql-password 'Cxoo1923' --sql-db mqtt --sql-type mariadb  -v

**Comment by zeesser** [comment]
responds :

./mqtt2sql.py:59: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
usage: mqtt2sql.py [-h] [-c <filename>] [--mqtt-host <host>]
                   [--mqtt-port <port>] [--mqtt-username <username>]
                   [--mqtt-password <password>]
                   [--mqtt-topic [<topic> [<topic> ...]]]
                   [--mqtt-cafile <cafile>] [--mqtt-certfile <certfile>]
                   [--mqtt-keyfile <keyfile>] [--mqtt-insecure]
                   [--mqtt-keepalive <sec>] [--sql-type <type>]
                   [--sql-host <host>] [--sql-port <port>]
                   [--sql-username <username>] [--sql-password <password>]
                   [--sql-db <db>] [--sql-table <table>]
                   [--sql-max-connection <num>] [--sql-connection-retry <num>]
                   [--sql-connection-retry-start-delay <sec>]
                   [--sql-transaction-retry <num>] [-l <filename>] [-d] [-v]
                   [-V]
mqtt2sql.py: error: argument --sql-type: invalid choice: 'mariadb' (choose from 'sqlite')

**Comment by zeesser** [comment]
./mqtt2sql.py --mqtt-host localhost --mqtt-topic '#' --sql-host localhost --sql-username root --sql-password 'Cxoo1923' --sql-db mqtt --sql-type mysql -v

Doesn't work either

**Comment by curzon01** [comment]
> ./mqtt2sql.py --mqtt-host localhost --mqtt-topic '#' --sql-host localhost --sql-username root --sql-password 'Cxoo1923' --sql-db mqtt --sql-type mysql -v
> 
> Doesn't work either

Ahhh, any message?

**Comment by curzon01** [comment]
> mysql=mariadb

is an invalid parameter

**Comment by zeesser** [comment]
Great! It works! you are genius!!!!!
It works very well. The strategy of the sql works well.
